# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11a14aa2f918a49ec22263959d814137634e791703ef1a7cc364e4cc0b4bd91eb488c6e45f3875a499f462423a6161ae5d85f8baac56c0b17c579bd86f74c40

test:
  secret_key_base: 12c6d0701e27d2dcf1fc7f534d2dad5b5439f22919b09de1d75d12b03412da9db9b6fa20d25ce94e8636cf6d90ee477a89956be1321dab99ddc939631a067401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
